version: '3'

volumes:
  atomic_aurora_backend_local_postgres_data: {}
  atomic_aurora_backend_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: atomic_aurora_backend_local_django
    container_name: atomic_aurora_backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
      - ./google-login-credentials.json:/app/google-login-credentials.json
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: atomic_aurora_backend_production_postgres
    container_name: atomic_aurora_backend_local_postgres
    volumes:
      - atomic_aurora_backend_local_postgres_data:/var/lib/postgresql/data
      - atomic_aurora_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: atomic_aurora_backend_local_docs
    container_name: atomic_aurora_backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./atomic_aurora_backend:/app/atomic_aurora_backend:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: atomic_aurora_backend_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: atomic_aurora_backend_local_redis

  celeryworker:
    <<: *django
    image: atomic_aurora_backend_local_celeryworker
    container_name: atomic_aurora_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: atomic_aurora_backend_local_celerybeat
    container_name: atomic_aurora_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: atomic_aurora_backend_local_flower
    container_name: atomic_aurora_backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
# redeploy
