# Generated by Django 4.2.5 on 2023-10-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("color", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productcolor")),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.producttype")),
            ],
        ),
    ]
