# Generated by Django 4.2.5 on 2023-11-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductType",
            new_name="ProductKind",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="type",
            new_name="kind",
        ),
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.ManyToManyField(to="pictures.picture"),
        ),
    ]
