# Generated by Django 4.2.5 on 2023-12-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0002_rename_producttype_productkind_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="picture",
        ),
        migrations.AddField(
            model_name="product",
            name="pictures",
            field=models.ManyToManyField(related_name="products", to="pictures.picture"),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.productcolor",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.productkind"
            ),
        ),
    ]
