# Generated by Django 4.2.5 on 2023-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("shows", "0002_show_pictures_show_unique_show_per_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="pictures",
            field=models.ManyToManyField(blank=True, to="pictures.picture"),
        ),
    ]
