# Generated by Django 4.2.5 on 2023-10-22 01:52

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_name_per_venue"
            ),
        ),
    ]
